"""Audit and reporting models."""
from dataclasses import dataclass, field
from datetime import datetime
from typing import List, Optional, Dict, Any
from models.signal import TradingSignal


@dataclass
class ExecutionResult:
    """Result of trade execution."""
    signal: TradingSignal
    order_id: Optional[str] = None
    executed: bool = False
    execution_time: Optional[datetime] = None
    error: Optional[str] = None
    fill_price: Optional[float] = None


@dataclass
class IterationSummary:
    """Summary of a single iteration."""
    iteration_number: int
    timestamp: datetime
    symbols_processed: List[str]
    signals_generated: int
    signals_validated: int
    signals_approved: int
    signals_executed: int
    execution_results: List[ExecutionResult] = field(default_factory=list)
    errors: List[str] = field(default_factory=list)
    duration_seconds: float = 0.0


@dataclass
class AuditReport:
    """Audit report generated by AuditAgent."""
    report_type: str  # "iteration", "daily", "weekly"
    timestamp: datetime
    summary: str  # LLM-generated narrative
    metrics: Dict[str, Any] = field(default_factory=dict)
    recommendations: Optional[str] = None

