"""Trading signal models."""
from dataclasses import dataclass, field
from datetime import datetime
from typing import Optional
from enum import Enum
import pandas as pd


class SignalAction(str, Enum):
    """Signal action types."""
    BUY = "BUY"
    SELL = "SELL"
    HOLD = "HOLD"


@dataclass
class TradingSignal:
    """
    Trading signal generated by Strategy Agent.
    
    This represents a recommendation to take action on a symbol.
    """
    symbol: str
    action: SignalAction
    strategy_name: str
    confidence: float  # 0.0 to 1.0
    timestamp: datetime
    price: Optional[float] = None  # Current/expected price
    stop_loss: Optional[float] = None
    take_profit: Optional[float] = None
    reasoning: Optional[str] = None  # LLM reasoning for the signal
    historical_data: Optional[pd.DataFrame] = field(default=None, repr=False)  # Historical data for validation
    qty: Optional[int] = None  # Calculated position size (in shares)
    risk_amount: Optional[float] = None  # Risk per trade in dollars
    approved: bool = False  # Whether signal passed risk checks
    
    def to_dict(self) -> dict:
        """Convert signal to dictionary."""
        return {
            "symbol": self.symbol,
            "action": self.action.value,
            "strategy_name": self.strategy_name,
            "confidence": self.confidence,
            "timestamp": self.timestamp.isoformat(),
            "price": self.price,
            "stop_loss": self.stop_loss,
            "take_profit": self.take_profit,
            "reasoning": self.reasoning,
            "qty": self.qty,
            "risk_amount": self.risk_amount,
            "approved": self.approved
        }

